# Generated by Django 6.0.3 on 2026-03-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='calorie_goal',
            field=models.PositiveIntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='carbs_goal',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fat_goal',
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='customuser',
            name='protein_goal',
            field=models.PositiveIntegerField(default=150),
        ),
    ]
