# Generated by Django 6.0.3 on 2026-03-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='local_gif',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/'),
        ),
    ]
